### ISSUE TITLE
Unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mpmclaugh** [jackcook/GCHelper#7] opened 2015-08-20 13:51 UTC
I am trying to use your GCHelper and I put the line GCHelper.sharedInstance.authenticateLocalUser() in my AppDelegate but when I run the project on the simulator I get an error right away.  I am new to Swift so I am probably doing something wrong.  Any idea what I need to do to resolve this?

Thanks!

GCHelper authenticationChanged]: unrecognized selector sent to instance 0x78681a20'
*** First throw call stack:
(
	0   CoreFoundation                      0x01656746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x012dba97 objc_exception_throw + 44
	2   CoreFoundation                      0x0165e705 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
	3   CoreFoundation                      0x015a5287 ___forwarding___ + 1047
	4   CoreFoundation                      0x015a4e4e _CF_forwarding_prep_0 + 14
	5   Foundation                          0x0083a079 __57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke + 40
	6   CoreFoundation                      0x01620be4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
	7   CoreFoundation                      0x0150d11b _CFXNotificationPost + 3051
	8   Foundation                          0x008295d6 -[NSNotificationCenter postNotificationName:object:userInfo:] + 98
	9   GameCenterFoundation                0x03d0ba63 __52-[GKDaemonProxy setLocalPlayer:authenticated:reply:]_block_invoke + 904
	10  libdispatch.dylib                   0x052355ea _dispatch_call_block_and_release + 15
	11  libdispatch.dylib                   0x05257bef _dispatch_client_callout + 14
	12  libdispatch.dylib                   0x0523d6bb _dispatch_main_queue_callback_4CF + 993
	13  CoreFoundation                      0x015af8ee __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	14  CoreFoundation                      0x0156d5f0 __CFRunLoopRun + 2256
	15  CoreFoundation                      0x0156ca5b CFRunLoopRunSpecific + 443
	16  CoreFoundation                      0x0156c88b CFRunLoopRunInMode + 123
	17  GraphicsServices                    0x044652c9 GSEventRunModal + 192
	18  GraphicsServices                    0x04465106 GSEventRun + 104
	19  UIKit                               0x026fd0b6 UIApplicationMain + 1526

**Comment by ExplicitG** [comment] 2015-08-21 14:52
I have the same problem

**Comment by jackcook** [comment] 2015-08-28 15:46
Sorry, I missed this. Are you using the version of GCHelper on the `master` or `xcode7` branch?

**Comment by mpmclaugh** [comment] 2015-08-28 15:48
I am using the master branch

**Comment by jackcook** [comment] 2015-08-29 03:05
I'm not getting the same issue, hmm. Is it definitely failing on the `authenticateLocalUser()` method, and not another one?

**Comment by rhhub** [comment] 2015-09-21 14:25
The problem is fixed when the authenticationChanged function is not private. I don't believe selectors can target private functions.

**Comment by jackcook** [comment] 2015-09-21 15:18
That is correct, thank you for pointing that out. I'll update the code tonight.

**Comment by jackcook** [comment] 2015-09-21 23:28
Should be fixed with version 0.2.6. Closing the issue for now.

**Closed by jackcook** 2015-09-21 23:28 UTC
